package com.waturnos.enums;

public enum BookingStatus {
	FREE, 
	PARTIALLY_RESERVED, 
	RESERVED, 
	CANCELLED, 
	COMPLETED, 
	NO_SHOW, 
	PENDING, 
	CONFIRMED,
	FREE_AFTER_CANCEL,
	RESERVED_AFTER_CANCEL,
	COMPLETED_AFTER_CANCEL,
	CANCELED_BY_PROVIDER,
	LOCK_BY_EXCLUSION
}
