package com.waturnos.notification.enums;

public enum NotificationType {
    RESET_PASSWORD,
    WELCOME_USER,
    CANCELBOOKING_BY_PROVIDER,
    APPOINTMENT_REMINDER,
    BOOKING_ASSIGN,
    BOOKING_REASSIGN,
    REMINDER_BOOKING,
    CLIENT_NOTIFICATION,
    ACCESS_TOKEN,
    WAITLIST_AVAILABLE
}